name: Code Review

on:
  pull_request:
    branches: [ "main" ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
        -Dsonar.organization=<YOUR_ORG> \
        -Dsonar.projectKey=<YOUR_PROJECT_KEY> \
        -Dsonar.python.version=3.x \
        -Dsonar.sources=src \
        -Dsonar.tests=tests
