name: Build, Test, and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Docs
      run: |
        sphinx-build -b html docs/ docs/_build/html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_ACTION_TOKEN }}
        publish_dir: docs/_build/html

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create junit directory
      run: mkdir -p junit
    - name: Run tests
      run: |
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov=src
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: junit/test-results.xml
